export default [
  // old
  {key: '--font-family', type: 0, value: '\'Ubuntu\', sans-serif'},
  {key: '--color-initial', type: 2, value: '#ffffff'},
  {key: '--color-primary', type: 2, value: '#9b4dca'},
  {key: '--color-secondary', type: 2, value: '#606c76'},
  {key: '--color-tertiary', type: 2, value: '#f4f5f6'},
  {key: '--color-quaternary', type: 2, value: '#d1d1d1'},
  {key: '--color-quinary', type: 2, value: '#e1e1e1'},
  {key: '--input-height', type: 1, value: '3', unit: 'rem'},
  {key: '--input-height-dense', type: 1, value: '2', unit: 'rem'},
  {key: '--input-border-radius', type: 1, value: '.4', unit: 'rem'},
  {key: '--input-border-radius-dense', type: 1, value: '.2', unit: 'rem'},

  // new
  // colors
  {key: '--xpr-color-primary', type: 2, value: '#b90063'},
  {key: '--xpr-color-on-primary', type: 2, value: '#ffffff'},
  {key: '--xpr-color-primary-container', type: 2, value: '#ffd9e2'},
  {key: '--xpr-color-on-primary-container', type: 2, value: '#3e001d'},
  {key: '--xpr-color-secondary', type: 2, value: '#0060a9'},
  {key: '--xpr-color-on-secondary', type: 2, value: '#ffffff'},
  {key: '--xpr-color-secondary-container', type: 2, value: '#d3e4ff'},
  {key: '--xpr-color-on-secondary-container', type: 2, value: '#001c38'},
  {key: '--xpr-color-tertiary', type: 2, value: '#984061'},
  {key: '--xpr-color-on-tertiary', type: 2, value: '#ffffff'},
  {key: '--xpr-color-tertiary-container', type: 2, value: '#ffd9e2'},
  {key: '--xpr-color-on-tertiary-container', type: 2, value: '#3e001d'},
  {key: '--xpr-color-error', type: 2, value: '#ba1a1a'},
  {key: '--xpr-color-error-container', type: 2, value: '#ffdad6'},
  {key: '--xpr-color-on-error', type: 2, value: '#ffffff'},
  {key: '--xpr-color-on-error-container', type: 2, value: '#410002'},
  {key: '--xpr-color-background', type: 2, value: '#f8fdff'},
  {key: '--xpr-color-on-background', type: 2, value: '#001f25'},
  {key: '--xpr-color-surface', type: 2, value: '#f8fdff'},
  {key: '--xpr-color-on-surface', type: 2, value: '#001f25'},
  {key: '--xpr-color-surface-variant', type: 2, value: '#f2dde1'},
  {key: '--xpr-color-on-surface-variant', type: 2, value: '#514347'},
  {key: '--xpr-color-outline', type: 2, value: '#837377'},
  {key: '--xpr-color-inverse-on-surface', type: 2, value: '#d6f6ff'},
  {key: '--xpr-color-inverse-surface', type: 2, value: '#00363f'},
  {key: '--xpr-color-inverse-primary', type: 2, value: '#ffb1c8'},
  {key: '--xpr-color-shadow', type: 2, value: '#000000'},
  {key: '--xpr-color-surface-tint', type: 2, value: '#b90063'},
  {key: '--xpr-color-outline-variant', type: 2, value: '#d5c2c6'},
  {key: '--xpr-color-scrim', type: 2, value: '#000000'},
];
